# Generated by Django 5.2 on 2025-06-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cardidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardidate_name', models.CharField(max_length=100)),
                ('cardidate_image', models.ImageField(upload_to='profiles/')),
            ],
        ),
    ]
